### ISSUE TITLE
how to calculate time interval ?

### ISSUE THREAD

**Issue by fwt1888** [thliebig/openEMS#84]
Hi, I came cross a problem. I want to know where time interval (i.e. dt) is defined or calculated in your code, because I think it is needed for calculation of f0 and fc.

**Comment by thliebig** [comment]
Well the calculation of dt is complicated (operator.cpp CalcTimestep). After the simulation it can be determined/read from several places.
Maybe you can say what you want to do?? 
And would have the forum been a better place for this question?

**Comment by fwt1888** [comment]
I want to set Gaussian excitation, but I'm not sure about the calculation of f0 and fc. I think timestep is needed in the forum related. Could you tell me the forum you use to calculate timestep? Thanks.

**Comment by MrHighVoltage** [comment]
AFAIK the maximum timestep is limited by the Grid settings (the minimum distance between two adjacent points). The timestep is, from my experience, much smaller then 1/(2*(fc+f0)), which is needed to keep within Nyquist–Shannon sampling theorem.
Apart from that, I don't think you really need to know the time interval for the calculation of f0 and fc, because OpenEMS does that by itself. You only have to check if the time-step (as a result of your grid-resolution) somehow matches your required simulation frequencies.
